In [1]:
import pandas as pd
import psycopg2
import pprint as pp

In [4]:
# Connect to database
db_name, ip, port, user_name, password, table_name = 'GHDataAnalytics', 'dopelytics.site', '5432', 'team', 'ZAQ!@#zaq123', '"beforeCluster"'
#192.168.132.223
conn = psycopg2.connect(f"dbname={db_name} user={user_name} host={ip} password={password}")

In [5]:
SQLQuery = pd.read_sql_query(f'SELECT * FROM {table_name};', conn)
df = pd.DataFrame(SQLQuery)

In [ ]:
# Save the top 25 rows to a csv on the server
df.head(25).to_csv(r'/home/team/Documents/Data-Oriented-Proposal-Engine/temp/first25from2014.csv')

In [ ]:
# Find the total dollars obligated
sumTDO = df['total_dollars_obligated'].sum()
print(f"sum is: ${sumTDO:,}")

In [7]:
# General attributes of each column
df.describe()

,level_0,modification_number,federal_action_obligation,base_and_exercised_options_value,base_and_all_options_value,action_date_fiscal_year,awarding_agency_code,recipient_duns,naics_code,number_of_offers_received,number_of_employees,annual_revenue,index,LevelOne,LevelTwo
count,64978.000000,64978.0,6.497800e+04,6.497800e+04,6.497800e+04,64978.000000,64978.0,6.497800e+04,64976.000000,64618.000000,6.450900e+04,6.450900e+04,64978.000000,64978.0,64978.000000
mean,32488.500000,0.0,5.273626e+05,1.011723e+06,2.170198e+06,2015.475192,97.0,3.560825e+08,550935.038876,3.410907,1.663044e+04,6.376570e+09,172.349641,2.0,2.405885
std,18757.677233,0.0,2.898573e+06,2.415107e+07,2.988914e+07,1.109697,0.0,3.556195e+08,83784.676190,16.268817,1.767994e+05,3.810678e+11,27.705022,0.0,0.243517
min,0.000000,0.0,0.000000e+00,-2.850000e+05,-1.007474e+06,2014.000000,97.0,1.001767e+06,111130.000000,0.000000,0.000000e+00,0.000000e+00,1.000000,2.0,2.100000
25%,16244.250000,0.0,1.003500e+04,1.100000e+04,1.285775e+04,2014.000000,97.0,7.747996e+07,541330.000000,1.000000,1.300000e+01,1.200000e+06,173.000000,2.0,2.300000
50%,32488.500000,0.0,6.600821e+04,7.488000e+04,8.794473e+04,2015.000000,97.0,1.370552e+08,541611.000000,1.000000,9.400000e+01,1.082711e+07,175.000000,2.0,2.300000
75%,48732.750000,0.0,2.748410e+05,3.434109e+05,4.799628e+05,2016.000000,97.0,7.878001e+08,541990.000000,3.000000,3.000000e+03,4.594750e+08,181.000000,2.0,2.500000
max,64977.000000,0.0,2.750216e+08,4.200000e+09,4.200000e+09,2017.000000,97.0,9.699998e+08,928120.000000,999.000000,3.600000e+07,9.600000e+13,223.000000,2.0,2.900000