In [1]:
# After playing with a subset of the Postgres table we ran some analysis to make sure
# we had the data that we needed. 

# Import libraries

import psycopg2
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
conn = psycopg2.connect(database='usaspending', user='postgres', password='gtown2019', host='127.0.0.1', port='5432')

In [3]:
sql_tbl_name = 'consolidated_data_filtered_bucketed'

In [4]:
sql_cols = ('federal_action_obligation, '
            'total_dollars_obligated, '
            'base_and_exercised_options_value, '
            'base_and_all_options_value, '
            'awarding_sub_agency_name, '
            'awarding_office_name, '
            'funding_sub_agency_name, '
            'funding_office_name, '
            'primary_place_of_performance_state_code, '
            'award_or_idv_flag, '
            'award_type, '
            'type_of_contract_pricing, '
            'dod_claimant_program_description, '
            'type_of_set_aside_code, '
            #'multi_year_contract, '
            #'dod_acquisition_program_description, ' too many NaN
            #'subcontracting_plan, ' too many NaN
            'contract_bundling, '
            #'evaluated_preference, ' too many NaN
            'national_interest_action, '
            #'cost_or_pricing_data, ' too many NaN
            'gfe_gfp, '
            'contract_financing, '
            'portfolio_group, '
            'product_or_service_code_description, '
            'naics_bucket_title, '
            'naics_description'
            )

In [5]:
df = pd.read_sql_query('SELECT ' + sql_cols + ' FROM ' + sql_tbl_name, con=conn)
df.shape

(35414, 22)

In [6]:
df = df[pd.notnull(df['type_of_set_aside_code'])]
df.shape

(35000, 22)

In [7]:
# Create conditional column to determine if set aside is YES or NO

def set_aside(c):
    if c['type_of_set_aside_code'] == 'NONE':
        return 0
    else:
        return 1

def contract_value(c):
    if c['base_and_exercised_options_value'] > 0:
        return c['base_and_exercised_options_value']
    elif c['base_and_all_options_value'] > 0:
        return c['base_and_all_options_value']
    elif c['total_dollars_obligated'] > 0:
        return c['total_dollars_obligated']
    elif c['federal_action_obligation'] > 0:
        return c['federal_action_obligation'] 
    else:
        return 0
    
df['set_aside'] = df.apply(set_aside, axis=1)
df['contract_value'] = df.apply(contract_value, axis=1)

del df['type_of_set_aside_code']
del df['base_and_exercised_options_value']
del df['base_and_all_options_value']
del df['total_dollars_obligated']
del df['federal_action_obligation']

df2 = df.dropna()
df2.shape

(27246, 19)

In [8]:
df3 = df2
df3 = pd.get_dummies(df2)
df3.head()

,set_aside,contract_value,awarding_sub_agency_name_DEFENSE ADVANCED RESEARCH PROJECTS AGENCY (DARPA),awarding_sub_agency_name_DEFENSE COMMISSARY AGENCY (DECA),awarding_sub_agency_name_DEFENSE CONTRACT MANAGEMENT AGENCY (DCMA),awarding_sub_agency_name_DEFENSE COUNTERINTELLIGENCE AND SECURITY AGENCY,awarding_sub_agency_name_DEFENSE FINANCE AND ACCOUNTING SERVICE (DFAS),awarding_sub_agency_name_DEFENSE HEALTH AGENCY (DHA),awarding_sub_agency_name_DEFENSE HUMAN RESOURCES ACTIVITY,awarding_sub_agency_name_DEFENSE INFORMATION SYSTEMS AGENCY (DISA),...,naics_description_TEXTILE BAG AND CANVAS MILLS,naics_description_THEATER COMPANIES AND DINNER THEATERS,naics_description_THIRD PARTY ADMINISTRATION OF INSURANCE AND PENSION FUNDS,naics_description_TOTALIZING FLUID METER AND COUNTING DEVICE MANUFACTURING,naics_description_TRANSLATION AND INTERPRETATION SERVICES,naics_description_TRAVEL AGENCIES,"naics_description_TRUCK, UTILITY TRAILER, AND RV (RECREATIONAL VEHICLE) RENTAL AND LEASING",naics_description_USED HOUSEHOLD AND OFFICE GOODS MOVING,naics_description_VOCATIONAL REHABILITATION SERVICES,naics_description_WOOD OFFICE FURNITURE MANUFACTURING
0,0,64925.82,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,4897.96,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,5618.14,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,163.92,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,0,220000.00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
cor = df3.corr()['set_aside'][:]
cor

In [ ]:
# Correlation with output variable
cor_target = abs(cor)
# Selecting highly correlated features
relevant_features = cor_target[cor_target>0.3]
relevant_features